CREATE TABLE CENTROS_FORENSES (
    ID_CENTROS_FORENSES INTEGER,
    NOMBRE VARCHAR(50),
    PAIS VARCHAR(50),
    NIVEL_SEGURIDAD VARCHAR(50),
    AUTOR_EXAMEN VARCHAR(150),
    CONSTRAINT PK_CENTROS_FORENSES PRIMARY KEY (ID_CENTROS_FORENSES),
    CONSTRAINT NN_CENTROS_FORENSES_NOMBRE CHECK (NOMBRE IS NOT NULL),
    CONSTRAINT NN_CENTROS_FORENSES_PAIS CHECK (PAIS IS NOT NULL),
    CONSTRAINT NN_CENTROS_FORENSES_NIVEL_SEGURIDAD CHECK (NIVEL_SEGURIDAD IS NOT NULL),
    CONSTRAINT NN_CENTROS_FORENSES_AUTOR_EXAMEN CHECK (AUTOR_EXAMEN IS NOT NULL) 
);


CREATE TABLE MUESTRAS_FORENSES  (
    ID_MUESTRAS_FORENSES INTEGER,
    CODIGO_CASO VARCHAR(50),
    TIPO_MUESTRA VARCHAR(50),
    FECHA_RECOGIDA DATE,
	ESTADO_CUSTODIA VARCHAR(50),
	ID_CENTROS_FORENSES INTEGER,
    AUTOR_EXAMEN VARCHAR(150),
    CONSTRAINT PK_MUESTRAS_FORENSES PRIMARY KEY (ID_MUESTRAS_FORENSES),
	CONSTRAINT FK_CENTROS_FORENSES_MUESTRAS_FORENSES FOREIGN KEY (ID_CENTROS_FORENSES) REFERENCES CENTROS_FORENSES(ID_CENTROS_FORENSES),
    CONSTRAINT NN_MUESTRAS_FORENSES_CODIGO_CASO CHECK (CODIGO_CASO IS NOT NULL),
    CONSTRAINT NN_MUESTRAS_FORENSES_TIPO_MUESTRA CHECK (TIPO_MUESTRA IS NOT NULL),
    CONSTRAINT NN_MUESTRAS_FORENSES_FECHA_RECOGIDA CHECK (FECHA_RECOGIDA IS NOT NULL),
	CONSTRAINT NN_MUESTRAS_FORENSES_ESTADO_CUSTODIA CHECK (ESTADO_CUSTODIA IS NOT NULL),
	CONSTRAINT NN_MUESTRAS_FORENSES_ID_CENTROS_FORENSES CHECK (ID_CENTROS_FORENSES IS NOT NULL),
    CONSTRAINT NN_MUESTRAS_FORENSES_AUTOR_EXAMEN CHECK (AUTOR_EXAMEN IS NOT NULL) 
);


CREATE TABLE INFORMES_FORENSES  (
    ID_INFORMES_FORENSES INTEGER,
    ADN_POSITIVO VARCHAR(50),
    NIVEL_RIESGO VARCHAR(50),
	CONCLUSION VARCHAR(50),
	ID_MUESTRAS_FORENSES INTEGER,
    AUTOR_EXAMEN VARCHAR(150),
    CONSTRAINT PK_INFORMES_FORENSES PRIMARY KEY (ID_INFORMES_FORENSES),
	CONSTRAINT FK_INFORMES_FORENSES_ID_MUESTRAS_FORENSES FOREIGN KEY (ID_MUESTRAS_FORENSES) REFERENCES MUESTRAS_FORENSES(ID_MUESTRAS_FORENSES),
    CONSTRAINT UQ_INFORMES_FORENSES_ID_MUESTRAS_FORENSES UNIQUE (ID_MUESTRAS_FORENSES),
    CONSTRAINT NN_INFORMES_FORENSES_ADN_POSITIVO CHECK (ADN_POSITIVO IS NOT NULL),
	CONSTRAINT NN_INFORMES_FORENSES_NIVEL_RIESGO CHECK (NIVEL_RIESGO IS NOT NULL),
    CONSTRAINT NN_INFORMES_FORENSES_CONCLUSION CHECK (CONCLUSION IS NOT NULL),
    CONSTRAINT NN_INFORMES_FORENSESID_MUESTRAS_FORENSES CHECK (ID_MUESTRAS_FORENSES IS NOT NULL),
    CONSTRAINT NN_INFORMES_FORENSES_AUTOR_EXAMEN CHECK (AUTOR_EXAMEN IS NOT NULL) 
);

