INSERT INTO CENTROS_FORENSES VALUES (1, 'Gato', 'Francia', 'Alto', 'DIEGO_JUSTO_DAM2');
INSERT INTO CENTROS_FORENSES VALUES (2, 'Loro', 'Italia', 'Alto', 'DIEGO_JUSTO_DAM2');
INSERT INTO CENTROS_FORENSES VALUES (3, 'Cacatua', 'España', 'Medio', 'DIEGO_JUSTO_DAM2');
INSERT INTO CENTROS_FORENSES VALUES (4, 'Perro', 'Francia', 'Bajo', 'DIEGO_JUSTO_DAM2');
INSERT INTO CENTROS_FORENSES VALUES (5, 'Leon', 'España', 'Medio', 'DIEGO_JUSTO_DAM2');

INSERT INTO MUESTRAS_FORENSES VALUES (1, 'X123', 'Sangre', '2025-09-11', 'Controlado', 2, 'DIEGO_JUSTO_DAM2');
INSERT INTO MUESTRAS_FORENSES VALUES (2, 'H152', 'Pelo', '2026-01-26', 'Controlado', 5, 'DIEGO_JUSTO_DAM2');
INSERT INTO MUESTRAS_FORENSES VALUES (3, 'V477', 'Sangre', '2025-01-30', 'Controlado', 1, 'DIEGO_JUSTO_DAM2');
INSERT INTO MUESTRAS_FORENSES VALUES (4, 'F544', 'Piel', '2025-05-28', 'Perdido', 4, 'DIEGO_JUSTO_DAM2');
INSERT INTO MUESTRAS_FORENSES VALUES (5, 'T122', 'Pelo', '2025-10-07', 'Perdido', 3, 'DIEGO_JUSTO_DAM2');

INSERT INTO INFORMES_FORENSES VALUES (1, 'Positivo', 'Alto', 'El paciente esta infectado', 1, 'DIEGO_JUSTO_DAM2');
INSERT INTO INFORMES_FORENSES VALUES (2, 'Negativo', 'Bajo', 'El paciente no esta infectado', 4, 'DIEGO_JUSTO_DAM2');
INSERT INTO INFORMES_FORENSES VALUES (3, 'Positivo', 'Medio', 'El paciente puede estar infectado', 3, 'DIEGO_JUSTO_DAM2');
INSERT INTO INFORMES_FORENSES VALUES (4, 'Positivo', 'Alto', 'El paciente esta infectado', 5, 'DIEGO_JUSTO_DAM2');
INSERT INTO INFORMES_FORENSES VALUES (5, 'Negativo', 'Bajo', 'El paciente no esta infectado', 2, 'DIEGO_JUSTO_DAM2');
